package com.hnjz.hzws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkflowServiceService", targetNamespace = "http://service.wf.horizon.com/", wsdlLocation = "http://192.168.10.68:8089/horizon-workflow-web/webservice/workflow/workflowService?wsdl")
public class WorkflowServiceService
    extends Service
{

    private final static URL WORKFLOWSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WORKFLOWSERVICESERVICE_EXCEPTION;
    private final static QName WORKFLOWSERVICESERVICE_QNAME = new QName("http://service.wf.horizon.com/", "WorkflowServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.68:8089/horizon-workflow-web/webservice/workflow/workflowService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKFLOWSERVICESERVICE_WSDL_LOCATION = url;
        WORKFLOWSERVICESERVICE_EXCEPTION = e;
    }

    public WorkflowServiceService() {
        super(__getWsdlLocation(), WORKFLOWSERVICESERVICE_QNAME);
    }

    public WorkflowServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKFLOWSERVICESERVICE_QNAME);
    }

    public WorkflowServiceService(URL wsdlLocation) {
        super(wsdlLocation, WORKFLOWSERVICESERVICE_QNAME);
    }

    public WorkflowServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKFLOWSERVICESERVICE_QNAME);
    }

    public WorkflowServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkflowServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WorkflowService
     */
    @WebEndpoint(name = "WorkflowServicePort")
    public WorkflowService getWorkflowServicePort() {
        return super.getPort(new QName("http://service.wf.horizon.com/", "WorkflowServicePort"), WorkflowService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkflowService
     */
    /*@WebEndpoint(name = "WorkflowServicePort")
    public WorkflowService getWorkflowServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wf.horizon.com/", "WorkflowServicePort"), WorkflowService.class, features);
    }*/
    private static URL __getWsdlLocation() {
        if (WORKFLOWSERVICESERVICE_EXCEPTION!= null) {
            throw WORKFLOWSERVICESERVICE_EXCEPTION;
        }
        return WORKFLOWSERVICESERVICE_WSDL_LOCATION;
    }

}