
package com.hnjz.hzws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkflowService", targetNamespace = "http://service.wf.horizon.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkflowService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pauseWorkMulti", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.PauseWorkMulti")
    @ResponseWrapper(localName = "pauseWorkMultiResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.PauseWorkMultiResponse")
    public String pauseWorkMulti(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handoverWork", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.HandoverWork")
    @ResponseWrapper(localName = "handoverWorkResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.HandoverWorkResponse")
    public boolean handoverWork(
        @WebParam(name = "arg0", targetNamespace = "")
        HashMap arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbTodo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHasTodoList", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHasTodoList")
    @ResponseWrapper(localName = "getHasTodoListResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHasTodoListResponse")
    public List<DbTodo> getHasTodoList(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateWork", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.UpdateWork")
    @ResponseWrapper(localName = "updateWorkResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.UpdateWorkResponse")
    public boolean updateWork(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbTodo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCReaderList", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetCReaderList")
    @ResponseWrapper(localName = "getCReaderListResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetCReaderListResponse")
    public List<DbTodo> getCReaderList(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbWork>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyStartList", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetMyStartList")
    @ResponseWrapper(localName = "getMyStartListResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetMyStartListResponse")
    public List<DbWork> getMyStartList(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSelectType", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetSelectType")
    @ResponseWrapper(localName = "getSelectTypeResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetSelectTypeResponse")
    public int getSelectType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyStartCount", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetMyStartCount")
    @ResponseWrapper(localName = "getMyStartCountResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetMyStartCountResponse")
    public int getMyStartCount(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClaimCount", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetClaimCount")
    @ResponseWrapper(localName = "getClaimCountResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetClaimCountResponse")
    public int getClaimCount(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbTodo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodoList", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetTodoList")
    @ResponseWrapper(localName = "getTodoListResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetTodoListResponse")
    public List<DbTodo> getTodoList(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbTodo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHaveReadList", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHaveReadList")
    @ResponseWrapper(localName = "getHaveReadListResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHaveReadListResponse")
    public List<DbTodo> getHaveReadList(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openInstanceService", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.OpenInstanceService")
    @ResponseWrapper(localName = "openInstanceServiceResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.OpenInstanceServiceResponse")
    public String openInstanceService(
        @WebParam(name = "arg0", targetNamespace = "")
        WorkParaBeanBase arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createInstanceService", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.CreateInstanceService")
    @ResponseWrapper(localName = "createInstanceServiceResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.CreateInstanceServiceResponse")
    public String createInstanceService(
        @WebParam(name = "arg0", targetNamespace = "")
        WorkParaBeanBase arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHaveReadCount", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHaveReadCount")
    @ResponseWrapper(localName = "getHaveReadCountResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHaveReadCountResponse")
    public int getHaveReadCount(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorkMaxVersion", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetWorkMaxVersion")
    @ResponseWrapper(localName = "getWorkMaxVersionResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetWorkMaxVersionResponse")
    public int getWorkMaxVersion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbTask>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTask", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetTask")
    @ResponseWrapper(localName = "getTaskResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetTaskResponse")
    public List<DbTask> getTask(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "closeInstance", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.CloseInstance")
    @ResponseWrapper(localName = "closeInstanceResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.CloseInstanceResponse")
    public void closeInstance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodoCount", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetTodoCount")
    @ResponseWrapper(localName = "getTodoCountResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetTodoCountResponse")
    public int getTodoCount(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getToBeReadCount", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetToBeReadCount")
    @ResponseWrapper(localName = "getToBeReadCountResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetToBeReadCountResponse")
    public int getToBeReadCount(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopWorkMulti", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.StopWorkMulti")
    @ResponseWrapper(localName = "stopWorkMultiResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.StopWorkMultiResponse")
    public String stopWorkMulti(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.hnjz.hzws.HashMap
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateWorkMulti", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.UpdateWorkMulti")
    @ResponseWrapper(localName = "updateWorkMultiResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.UpdateWorkMultiResponse")
    public HashMap updateWorkMulti(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operatorService", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.OperatorService")
    @ResponseWrapper(localName = "operatorServiceResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.OperatorServiceResponse")
    public String operatorService(
        @WebParam(name = "arg0", targetNamespace = "")
        WorkParaBeanBase arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveHandoverWork", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.ReceiveHandoverWork")
    @ResponseWrapper(localName = "receiveHandoverWorkResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.ReceiveHandoverWorkResponse")
    public String receiveHandoverWork(
        @WebParam(name = "arg0", targetNamespace = "")
        List<DbHandover> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteWorkMulti", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.DeleteWorkMulti")
    @ResponseWrapper(localName = "deleteWorkMultiResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.DeleteWorkMultiResponse")
    public boolean deleteWorkMulti(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbTodo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getToBeReadList", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetToBeReadList")
    @ResponseWrapper(localName = "getToBeReadListResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetToBeReadListResponse")
    public List<DbTodo> getToBeReadList(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCReaderCount", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetCReaderCount")
    @ResponseWrapper(localName = "getCReaderCountResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetCReaderCountResponse")
    public int getCReaderCount(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbLog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHistory", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHistory")
    @ResponseWrapper(localName = "getHistoryResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHistoryResponse")
    public List<DbLog> getHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "replaceWork", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.ReplaceWork")
    @ResponseWrapper(localName = "replaceWorkResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.ReplaceWorkResponse")
    public boolean replaceWork(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHasTodoCount", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHasTodoCount")
    @ResponseWrapper(localName = "getHasTodoCountResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetHasTodoCountResponse")
    public int getHasTodoCount(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agentUserSet", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.AgentUserSet")
    @ResponseWrapper(localName = "agentUserSetResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.AgentUserSetResponse")
    public boolean agentUserSet(
        @WebParam(name = "arg0", targetNamespace = "")
        HashMap arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pauseWork", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.PauseWork")
    @ResponseWrapper(localName = "pauseWorkResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.PauseWorkResponse")
    public boolean pauseWork(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopWork", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.StopWork")
    @ResponseWrapper(localName = "stopWorkResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.StopWorkResponse")
    public boolean stopWork(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteWork", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.DeleteWork")
    @ResponseWrapper(localName = "deleteWorkResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.DeleteWorkResponse")
    public boolean deleteWork(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hnjz.hzws.DbTodo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClaimList", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetClaimList")
    @ResponseWrapper(localName = "getClaimListResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.GetClaimListResponse")
    public List<DbTodo> getClaimList(
        @WebParam(name = "arg0", targetNamespace = "")
        TodoPara arg0);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "replaceAuthor", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.ReplaceAuthor")
    @ResponseWrapper(localName = "replaceAuthorResponse", targetNamespace = "http://service.wf.horizon.com/", className = "com.hnjz.hzws.ReplaceAuthorResponse")
    public boolean replaceAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
